// Generated by CoffeeScript 1.6.3
(function() {
  var restart;

  restart = function() {
    var timer;
    return timer = setTimeout(function() {
      var switchButton, target;
      target = document.querySelector(".d-Fa-uc-A.BF");
      if (!target) {
        return restart();
      }
      switchButton = "<div role=\"button\" id=\"switch-user\" class=\"c-N-K a-b a-b-ga d-Dc-b DF a-b-U-Z\" tabindex=\"0\" style=\"-webkit-user-select: none;margin-top:20px !important\">Switch User?</div>";
      target.insertAdjacentHTML("beforeend", switchButton);
      return document.getElementById("switch-user").addEventListener("click", function() {
        var found;
        found = window.location.search.indexOf("authuser=");
        if (~found && window.location.search[found + 9] === "1") {
          return window.location.search = "authuser=0";
        } else {
          return window.location.search = "authuser=1";
        }
      });
    }, 1000);
  };

}).call(this);
